version: '3.3'
services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5434/autoadmin
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=p$ssw@rd
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=autoadmin
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=p$ssw@rd
      - PGPORT=5434
    ports:
      - "5434:5434"
    command: ["postgres", "-c", "port=5434"]